package tech.msociety.terawhere.utils.faker;

class FakerName {
    static final String[] NAMES = new String[]{
            "Shawanna Pearce",
            "Ramona Merlos",
            "Cecille Furlow",
            "Margaretta Visser",
            "Lilli Eastham",
            "Delsie Bidwell",
            "Leopoldo Holiday",
            "Ahmad Francese",
            "Loretta Sachs",
            "Halina Palmer",
            "Yoshiko Diemer",
            "Brittanie Junkin",
            "Rodney Cottman",
            "Otelia Crockett",
            "Santo Delafuente",
            "Deana Wygant",
            "Whitley Berquist",
            "Emeline Goodpaster",
            "Maira Manis",
            "Adaline Peres",
            "Aja Pastore",
            "Illa Haris",
            "Gwendolyn Kern",
            "Vikki Laver",
            "Jule Shuman",
            "Kathey Marmolejo",
            "Vivian Palomo",
            "Ernesto Laplante",
            "Bethann Delahanty",
            "Isabella Dalpiaz",
            "Clemencia Brodt",
            "Quentin Avans",
            "Kenneth Pareja",
            "Sanda Littlepage",
            "Mellisa Presson",
            "Christal Inoue",
            "Olevia Endres",
            "Shandra Steed",
            "Dolores Kapoor",
            "Ebony Gerena",
            "Niki Barcenas",
            "Levi Nowack",
            "Lashell Brandon",
            "Oralee Marc",
            "Hector Flatley",
            "Brady Dibernardo",
            "Leida Audia",
            "Brain Brumbaugh",
            "Jalisa Aldaco",
            "Sherell Rockhold",
    };
}
