# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Terawhere' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Terawhere
  pod 'Firebase/Core'  

  target 'TerawhereTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TerawhereUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
